name: Main
on: [push, pull_request]
jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
# host info
    - run: docker info
    - run: docker version
    - run: cat /proc/cpuinfo
# test
    - run: ./hack/translate-dockerfile-runopt-directive.sh < Dockerfile | DOCKER_BUILDKIT=1 docker build -f - -t aind/aind:local .
    - run: sudo ./hack/install-kmod.sh
    - run: docker run -td --name aind --privileged -p 5900:5900 -v /lib/modules:/lib/modules:ro aind/aind:local
    - run: docker run -td --name aind-novnc --privileged -p 8080:8080 -e "NOVNC=1" -v /lib/modules:/lib/modules:ro aind/aind:local
    - run: timeout 60 sh -exc "until docker exec aind pgrep -f org.anbox.appmgr; do sleep 10; done"
# diagnosis
    - run: docker exec aind ps -ef
      if: always()
    - run: docker exec aind-novnc ps -ef
      if: always()
    - run: docker logs aind
      if: always()
    - run: docker logs aind-novnc
      if: always()
    - run: docker exec aind cat /var/lib/anbox/logs/console.log
      if: always()
    - run: docker exec aind-novnc cat /var/lib/anbox/logs/console.log
      if: always()
# capture screenshot and upload as an artifact
    - run: docker exec aind apt install scrot -y
    - run: docker exec aind-novnc apt install scrot -y
    
    - run: docker exec aind env DISPLAY=:0 scrot /ss.png
    - run: docker exec aind-novnc env DISPLAY=:0 scrot /ss.png
    - run: docker cp aind:/ss.png aind_ss.png
    - run: docker cp aind-novnc:/ss.png aind_novnc_ss.png

    - run: docker exec aind sh -c 'echo "anbox launch --package=com.aurora.store --component=com.aurora.store.ui.main.AuroraActivity" | su user'
    - run: docker exec aind env DISPLAY=:0 scrot /ss_aurora.png
    - run: docker cp aind:/ss_aurora.png aind_ss_aurora.png

    - run: docker exec aind-novnc sh -c 'echo "anbox launch --package=org.mozilla.firefox --component=org.mozilla.gecko.BrowserApp" | su user'
    - run: docker exec aind-novnc env env DISPLAY=:0 xterm -class UXTerm -title uxterm -u8 -e /bin/bash -c 'curl 127.0.0.1:8080 -v || echo "fail" && sleep 60'
    - run: docker exec aind-novnc env DISPLAY=:0 scrot /ss_firefox_chkhttp.png
    - run: docker cp aind-novnc:/ss_firefox_chkhttp.png

    - uses: actions/upload-artifact@v2
      with:
        name: Screenshot
        path: |
          aind_*.png